USE [CONTROLE_VENDAS]

CREATE TABLE [TABELA_VENDEDORES](
	[CODIGO_VENDEDOR] int NOT NULL PRIMARY KEY IDENTITY,
	[NOME_VENDEDOR] varchar(100) NOT NULL,
	[PERCENTUAL_COMISSAO] float NOT NULL,
	[DATA_ADMISSAO] date NULL,
	[STATUS_FERIAS] bit NOT NULL,
	[USUARIO] varchar(50) NOT NULL,
	[SENHA] varchar(50) NOT NULL
	)


