USE [CONTROLE_VENDAS]

CREATE TABLE [TABELA_PRODUTOS](
	[CODIGO_PRODUTO] int NOT NULL PRIMARY KEY IDENTITY (1, 2),
	[NOME_PRODUTO] varchar(50) NOT NULL,
	[EMBALAGEM] varchar(20) NOT NULL,
	[TAMANHO] varchar(10) NOT NULL,
	[SABOR] varchar(20) NOT NULL,
	[PRECO_DE_LISTA] smallmoney NOT NULL)



