CREATE TABLE TABELA_VENDAS(

CODIGO_VENDA INT PRIMARY KEY IDENTITY NOT NULL,

CODIGO_CLIENTE INT NOT NULL
CONSTRAINT FK_CLIENTES_VENDAS FOREIGN KEY REFERENCES [TABELA_CLIENTES] (CODIGO_CLIENTE),

CODIGO_PRODUTO INT NOT NULL
CONSTRAINT FK_PRODUTOS_VENDAS FOREIGN KEY REFERENCES [TABELA_PRODUTOS] (CODIGO_PRODUTO),

CODIGO_VENDEDOR INT NOT NULL
CONSTRAINT FK_VENDEDOR_VENDAS FOREIGN KEY REFERENCES [TABELA_VENDEDORES] (CODIGO_VENDEDOR),

CREDITO_LOJA DECIMAL NOT NULL,
DATA_HORA DATETIME NOT NULL,
CLIENTE_PRIMEIRA_COMPRA DECIMAL(18,0) NOT NULL,
PRODUTO_PRIMEIRA_COMPRA DECIMAL(18,0) NOT NULL,
QUANTIDADE INT NOT NULL,
PRECO_TOTAL DECIMAL(18,2) NOT NULL
)
