CREATE TABLE TABELA_CLIENTE_COMPRAS(

CODIGO_COMPRA INT PRIMARY KEY IDENTITY NOT NULL,

CODIGO_VENDA INT NULL
CONSTRAINT FK_VENDAS_CLIENTE_COMPRAS FOREIGN KEY REFERENCES [TABELA_VENDAS] (CODIGO_VENDA),

CODIGO_CLIENTE INT NOT NULL
CONSTRAINT FK_CLIENTES_CLIENTE_COMPRAS FOREIGN KEY REFERENCES [TABELA_CLIENTES] (CODIGO_CLIENTE),

CODIGO_PRODUTO INT NOT NULL
CONSTRAINT FK_PRODUTOS_CLIENTE_COMPRAS FOREIGN KEY REFERENCES [TABELA_PRODUTOS] (CODIGO_PRODUTO),

NOME_PRODUTO VARCHAR(50) NOT NULL,
QUANTIDADE INT NOT NULL,
CREDITO_LOJA DECIMAL(18,0) NOT NULL,
LIMITE_CREDITO MONEY NULL,
PRECO DECIMAL(18,2) NOT NULL,
PRECO_TOTAL DECIMAL(18,2) NOT NULL,
DATA_HORA DATETIME NOT NULL,
CLIENTE_PRIMEIRA_COMPRA DECIMAL(18,0) NOT NULL
)