USE [CONTROLE_VENDAS]

CREATE TABLE [TABELA_PRODUTO_ESTOQUE](
	[CODIGO_ESTOQUE] int NOT NULL PRIMARY KEY IDENTITY,

	CODIGO_PRODUTO INT NOT NULL
	CONSTRAINT FK_PRODUTOS_PRODUTO_ESTOQUE FOREIGN KEY REFERENCES [TABELA_PRODUTOS] (CODIGO_PRODUTO),

	[NOME_PRODUTO] varchar(50) NOT NULL,
	[EMBALAGEM] varchar(20) NOT NULL,
	[TAMANHO] varchar(10) NOT NULL,
	[SABOR] varchar(20) NOT NULL,
	[QUANTIDADE_EM_ESTOQUE] decimal(18,0) NOT NULL,
	PRODUTO_PRIMEIRA_COMPRA decimal(18,0) NOT NULL
)